'use client'

import Head from 'next/head'
import Image from 'next/image'

export default function Hero() {
  return (
    <div className="bg-[#FCF8F3] min-h-screen">
      <Head>
        <title>50+ Beautiful Rooms Inspiration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4 py-16">
        <div className="flex items-center justify-between space-x-8">
          {/* Text Section (Left Side) */}
          <div className="flex-1">
            <h1 className="text-4xl w-[400px] font-bold text-gray-800 mb-4">
              50+ Beautiful rooms inspiration
            </h1>
            <p className="text-lg text-gray-600  w-[400px] mb-8">
              Our designer already made a lot of beautiful
              prototypes of rooms that inspire you
            </p>
            <button className="bg-[#B88E2F] hover:bg-yellow-500 text-white font-bold py-2 px-4 rounded">
              Explore More
            </button>
          </div>

          {/* Image Section (Right Side) */}
          <div className="flex-1 relative w-full h-[550px] ">
            <Image
              src="/images/room1.png"
              alt="Room Example"
              layout="fill"
              objectFit="cover"
              className=" shadow-lg"
            />
          </div>
        </div>
      </main>
    </div>
  )
}
